import { BrainCircuit, AlertTriangle } from "lucide-react";


export default function InfoCard() {
  return (
    <section className="info-card-section max-w-2xl mx-auto space-y-4">
      {/* API status alert */}
      <div
        role="alert"
        aria-live="polite"
        className="w-full bg-yellow-900/60 border-l-4 border-yellow-400 text-yellow-100 rounded-lg p-3 flex items-start gap-3"
      >
        <AlertTriangle className="w-6 h-6 text-yellow-300 mt-0.5 flex-shrink-0" />
        <div className="text-sm">
          <p className="font-semibold">API currently inactive</p>
          <p className="text-yellow-100/90">Only historical statistics are currently available — new match predictions are not being generated at this time. Please check back later.</p>
        </div>
      </div>

      {/* <div className="info-card bg-slate-800/50 backdrop-blur-sm border border-white/10 rounded-xl p-4 flex items-center justify-center space-x-3">
        <BrainCircuit className="w-6 h-6 text-cyan-400" />
        <p className="text-slate-300 text-sm md:text-base">Predictions are generated by our advanced AI using statistical analysis.</p>
      </div> */}
    </section>
  );
}
